### ISSUE TITLE
Naming conflict with GNU poke

### ISSUE THREAD

**Issue by wasamasa** [RyanMillerC/poke-mode#7]
I thought at first this was a mode integrating this GNU project: http://www.jemarch.net/poke

Would you consider renaming it so that it's obvious what it stands for?

**Comment by progfolio** [comment]
suggestion: pokémodeline or pokemon-line

**Comment by RyanMillerC** [comment]
Now would be the best time to change since I haven’t posted this project anywhere outside of MELPA.

Could do package name `poke-line` and mode name `poke-line-mode`. I want to avoid the é since it could be confusing.

**Comment by jemarch** [comment]
Thanks for the rename.  Much appreciated :)
